Labs 1-3
sergej-kucharev/cn-2020 pull request #187
Opened 2020-05-09 09:49 UTC by alikrutko

2020-05-09 10:08 UTC, sergej-kucharev requested changes
"../ Krutko Alisa/..." -> "../Krutko Alisa/..." - удалите лишний пробел в начале

2020-05-09 10:09 UTC, sergej-kucharev requested changes
CN_lab2.pdf - неверное имя для отчета

2020-05-09 10:17 UTC, alikrutko reviewed
А как это сделать?

2020-05-09 11:00 UTC, sergej-kucharev requested changes
вы добавили, но не изменили ранее запрошенные некорректные изменения

2020-05-16 22:50 UTC, sergej-kucharev requested changes
Папка с пробелом в начале все еще осталась (
Я так понимаю у вас не получается самостоятельно свяжитесь со мной и попробуем по ремоуту это исправить

2020-05-18 12:58 UTC, alikrutko commented
> Папка с пробелом в начале все еще осталась (
> Я так понимаю у вас не получается самостоятельно свяжитесь со мной и попробуем по ремоуту это исправить

да, я не могу отредактировать ничего. Вам можно написать в телеграмме?

2020-05-22 13:57 UTC, sergej-kucharev approved these changes

2020-05-22 13:58 UTC, merged