ShakhvorostovaVlada
sergej-kucharev/cn-2020 pull request #23
Opened 2020-03-22 12:11 UTC by vdshakh

Labs

2020-03-28 22:58 UTC, sergej-kucharev requested changes
1) Каждый заливает сам СВОИ файлы!!!
2) Исправить структуру влоенность
3) Все протоколы должны дублироваться в PDF формате

2020-05-16 22:45 UTC, sergej-kucharev commented
Я так понимаю у вас не получается правильно сформировать ваши изменения и залить их в git - сейчас картинка странная ...

2020-05-16 23:13 UTC, vdshakh commented
Здравствуйте. Мне казалось, что все в порядке. Второе изменение #36
принято, хотя сейчас вижу, что в папке документы и с правильным, и с
неправильным названием. Подскажите как быть, возможно, лучше удалить, чтобы
я загрузила только правильный вариант?

вс, 17 мая 2020 г. в 01:45, Sergej <notifications@github.com>:

> Я так понимаю у вас не получается правильно сформировать ваши изменения и
> залить их в git - сейчас картинка странная ...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sergej-kucharev/cn-2020/pull/23#issuecomment-629715378>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO42P2HOLD5CCNXRLJIPEETRR4JSNANCNFSM4LRIVBGA>
> .
>

2020-05-18 21:20 UTC, sergej-kucharev commented
в любом случае надо исправить и сделайте что-то с этим пулл рекветом - а то висит и не туда и не сюда ...

2020-05-18 21:35 UTC, vdshakh commented
Уже исправила. По крайней мере, при проверке всех лаб форматы pdf и docx
подсвечиваются зелёным.
Этот пул можно просто удалить?

вт, 19 мая 2020 г. в 00:20, Sergej <notifications@github.com>:

> в любом случае надо исправить и сделайте что-то с этим пулл рекветом - а
> то висит и не туда и не сюда ...
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sergej-kucharev/cn-2020/pull/23#issuecomment-630441395>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO42P2H3HYUNRECH6JQ5RHDRSGRCVANCNFSM4LRIVBGA>
> .
>

2020-05-30 10:11 UTC, sergej-kucharev requested changes
почему правки в двух папаках ?

2020-06-03 09:43 UTC, sergej-kucharev approved these changes

2020-06-03 09:43 UTC, merged